name: Build and Deploy Function App

on:
    push:
        branches:
            - main

jobs:

  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # Deploys Azure resources (e.g., Function App, Resource Group, Storage Account) defined in the Bicep template
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group eventdriapi-rg \
            --template-file ./infra/main.bicep \
            --parameters functionAppName=eventbasedapi-app location=westeurope storageAccountName=accstorenameapi \
            --output none --debug
  build-and-deploy:
      needs: deploy-infra
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
          - name: Setup NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.0.x'
          
          - name: Restore and Build Function App
            run: dotnet publish ./src/cardswipe/cardswipe.csproj -c Release -o ./src/cardswipe

          - name: Publish to Azure Function App
            run: | 
              func azure functionapp publish cardswipe 

          # - name: Deploy to Azure Function App
          #   uses: Azure/functions-action@v1
          #   with:
          #     app-name: eventbasedAPI-App
          #     package: ./publish
          #     publish-profile: ${}
