name: Build and Deploy Function App

on:
    push:
        branches:
            - main

jobs:

  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # Deploys Azure resources (e.g., Function App, Resource Group, Storage Account) defined in the Bicep template
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group eventdriapi-rg \
            --template-file ./infra/main.bicep \
            --parameters functionAppName=eventbasedapi-app location=westeurope storageAccountName=accstorenameapi \
            --output none --debug
  
  build-and-deploy:
    needs: deploy-infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Azure Function Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restore and Build Function App
        run: |
          cd src/cardswipe
          dotnet publish -c Release -o ./publish

      - name: Publish to Azure Function App
        run: |
          func azure functionapp publish eventbasedapi-app --dotnet --publish-local-settings -i -c Release --no-build
