name: Build and Deploy Function App

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Setup NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore and Build Function App
              run: dotnet publish ./src/<your-func-folder>.csproj -c Release -o ./publish

            - name: Deploy to Azure Function App
              uses: Azure/functions-action@v1
              with:
                app-name: <your-app-name>
                package: ./publish
                publish-profile: ${}